name: Atnaujinti Renginius

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch: # Ši eilutė sukuria paleidimo mygtuką!

permissions:
  contents: write 

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  update-events:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repozitoriją
        uses: actions/checkout@v4

      - name: Paruošti Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Įdiegti bibliotekas
        run: pip install requests beautifulsoup4

      - name: Paleisti skriptą
        run: python update_events.py

      - name: Išsaugoti (Commit) pakeitimus
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "actions@github.com"
          git add index.html
          git diff-index --quiet HEAD || git commit -m "Automatinis renginių atnaujinimas"
          git push
